{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fbe2cac-4eda-4d85-a244-d57dacc55b96",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, jsonify\n",
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# ---------------------------\n",
    "# Initialize Flask app\n",
    "# ---------------------------\n",
    "app = Flask(__name__)\n",
    "\n",
    "# ---------------------------\n",
    "# Load model and features\n",
    "# ---------------------------\n",
    "MODEL_PATH = \"../output/final_model.pkl\"\n",
    "FEATURES_PATH = \"../output/features.pkl\"\n",
    "\n",
    "final_model = joblib.load(MODEL_PATH)\n",
    "FEATURES = joblib.load(FEATURES_PATH)\n",
    "\n",
    "# ---------------------------\n",
    "# Get exact feature names used during training\n",
    "# (CRITICAL to avoid feature mismatch)\n",
    "# ---------------------------\n",
    "MODEL_FEATURES = final_model.booster_.feature_name()\n",
    "\n",
    "# ---------------------------\n",
    "# Health check route\n",
    "# ---------------------------\n",
    "@app.route(\"/\", methods=[\"GET\"])\n",
    "def home():\n",
    "    return jsonify({\n",
    "        \"status\": \"API is running\",\n",
    "        \"model\": \"LightGBM Predictive Maintenance Model\"\n",
    "    })\n",
    "\n",
    "# ---------------------------\n",
    "# Prediction endpoint\n",
    "# ---------------------------\n",
    "@app.route(\"/predict\", methods=[\"POST\"])\n",
    "def predict():\n",
    "    try:\n",
    "        data = request.get_json()\n",
    "\n",
    "        if data is None:\n",
    "            return jsonify({\"error\": \"Invalid JSON input\"}), 400\n",
    "\n",
    "        # Convert input JSON to DataFrame\n",
    "        df = pd.DataFrame([data])\n",
    "\n",
    "        # Ensure all required features exist\n",
    "        missing_features = [f for f in MODEL_FEATURES if f not in df.columns]\n",
    "\n",
    "        if missing_features:\n",
    "            return jsonify({\n",
    "                \"error\": \"Missing required features\",\n",
    "                \"missing_features\": missing_features\n",
    "            }), 400\n",
    "\n",
    "        # Select features in correct order\n",
    "        X = df[MODEL_FEATURES]\n",
    "\n",
    "        # Predict probability (failure = class 1)\n",
    "        failure_prob = final_model.predict_proba(X)[0][1]\n",
    "\n",
    "        return jsonify({\n",
    "            \"failure_probability\": round(float(failure_prob), 4),\n",
    "            \"risk_level\": \"HIGH\" if failure_prob >= 0.5 else \"LOW\"\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\n",
    "            \"error\": str(e)\n",
    "        }), 500\n",
    "\n",
    "# ---------------------------\n",
    "# Run Flask app\n",
    "# ---------------------------\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host=\"0.0.0.0\", port=5003, debug=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c34c362-b19e-4bff-a5ac-ccc8c789cb7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.route(\"/features\", methods=[\"GET\"])\n",
    "def features():\n",
    "    return jsonify({\n",
    "        \"required_features\": MODEL_FEATURES\n",
    "    })\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ac782c4-c78a-461b-8e8e-1c5cc7a03490",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
